<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TestCase;

class IndexTest extends TestCase
{
    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();
    }

    /**
     * Teste básico que simula o usuário visitando a página home do dashboard.
     *
     * @return void
     */
    public function testIndex()
    {
        //Quando o usuário visita a página home do metodo home do IndexController
        $this->actingAs($this->user)
            ->get(route('dashboard.index.home'));

        $this->assertAuthenticated();
    }
}
